# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Geolocation' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleMaps'
  pod 'IQKeyboardManagerSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  use_frameworks!
end
