# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Geolocation' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleMaps'
  pod 'IQKeyboardManagerSwift'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod "IDPCastable"
  pod "IDPRootViewGettable", :git => 'https://github.com/idapgroup/IDPRootViewGettable.git'
  use_frameworks!
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end